name: ba
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.12
  - pip=25.1
  - cudatoolkit
  - numpy
  - matplotlib
  - notebook
  - scikit-image
  - tqdm
  - colmap=3.11.1
  - sqlite
  - plyfile
  - pip:
    - mitsuba
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch
    - torchvision
    - torchaudio