name: ba
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - pip=24.2
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit
  - numpy
  - matplotlib
  - notebook
  - ipywidgets
  - scikit-image
  - tqdm
  - colmap=3.11.1
  - sqlite
  - plyfile
  - commentjson
  - pybind11
  - pyquaternion
  - pip:
    - mitsuba
    - submodules/gaussian-splatting/submodules/diff-gaussian-rasterization
    - submodules/gaussian-splatting/submodules/simple-knn
    - submodules/gaussian-splatting/submodules/fused-ssim
    - opencv-python
    - joblib
